### ISSUE TITLE
Fails on minimal stack.yaml

### ISSUE THREAD

**Issue by philipcraig** [ndmitchell/weeder#1]
Fails on a ``stack.yaml`` that only consists of a one line Windows file containing just:
``resolver: nightly-2017-04-24``

Error is:

```
> weeder .
weeder: Failed to parse stack file
CallStack (from HasCallStack):
  error, called at src\Stack.hs:19:15 in main:Stack
```

Forcing a new line at the end of the file didn't help.

**Comment by ndmitchell** [comment]
Which projects does that stack file refer to?

**Comment by philipcraig** [comment]
An example could be found at: https://github.com/philipcraig/hutton

**Comment by ndmitchell** [comment]
Thanks! Fixed (and that repo has no weeds, FWIW)
