### ISSUE TITLE
Doesn't seem to understand generated modules

### ISSUE THREAD

**Issue by glguy** [ndmitchell/weeder#10]
I seem to get incorrect output running weeder on a project that uses alex and happy. I have another project that uses hsc2hs with the same problem.

I don't know if it's possible to do anything about this, but it would be neat if it could be supported.

Example project: https://hackage.haskell.org/package/config-value

```
= Package config-value =

== Section library ==
Excessive other-modules entry
* Config.LexerUtils
Missing other-modules entry
* Config.Lexer
* Config.Parser
Module not compiled
* Config.Lexer
* Config.Parser
Weeds exported
* Config.LexerUtils
  - Action
  - AlexInput
  - InComment
  - InCommentString
  - InNormal
  - InString
  - LexerMode
  - alexGetByte
  - byteForChar
  - endMode
  - eofAction
  - errorAction
  - floating
  - move
  - nestMode
  - number
  - park
  - section
  - startPos
  - startString
  - token
  - token_
  - untermString
```

**Comment by ndmitchell** [comment]
I just pushed some changes. After that it says:

```
= Package config-value =

== Section library ==
Weeds exported
* Config.LexerUtils
  - byteForChar
  - move
  - park
```

Which looks accurate.

I'll probably make a release in a few days time.

**Comment by ethercrow** [comment]
I just hit the same issue trying to use weeder on yi. Generated lexer files are reported as not compiled. Please make a release.

I must say I was very pleasantly surprised that weeder works with multiproject stack files out of the box! Thanks Neil!

**Comment by ndmitchell** [comment]
Thanks for the prod @ethercrow, had totally slipped my mind - now released. Note that it has multiproject support, but basically considers each project in isolation (and it has to be that way, due to what information goes in the .hi files).
