### ISSUE TITLE
Weeder doesn't respect `STACK_YAML` environment variable

### ISSUE THREAD

**Issue by bitemyapp** [ndmitchell/weeder#13]
I mostly work on monorepos that have one `stack.yaml` file at the top level of a multi-package git repository. Accordingly, most of my Makefiles look something like:

```Make
stack_yaml = STACK_YAML="../stack.yaml"
stack = $(stack_yaml) stack
package = my-pkg
version = v0.0.5.9
```

What I'd like to be able to do is to use `STACK_YAML="../stack.yaml"` but it seems to unconditionally look for the file at `./` which makes running it on a single package impossible for the moment.

**Comment by ndmitchell** [comment]
I'm sure I can do something here, but first question, why not just run over all the projects at once? Does your root `stack.yaml` list all the child projects? Are you hoping to add a Weeder target that only runs on a single project? You can run `weeder ..` to check the parent project, but it sounds like maybe what you want is an option to restrict which projects are looked at?

**Comment by mitchty** [comment]
One other use case where this is needed that I encountered straight away: I use Nix on osx to do general testing/development and that requires changes to stack.yaml to get to work. When I run off the same checkout to build something for say linux sans nix I strip that config out of stack.yaml and then set STACK_YAML to that copied/stripped config file without nix references.

**Comment by pepeiborra** [comment]
This is affecting us as well in production, where we want to have separate stack.yaml files for Windows and Linux (some projects only build in one of the two os's, guess which).

**Comment by pepeiborra** [comment]
FWIW `stack path --config-location` will give you the path to the stack.yaml file

**Comment by ndmitchell** [comment]
Thanks @pepeiborra - I'll give that solution a try, as it makes the code nice and generic.

**Comment by ndmitchell** [comment]
I believe weeder let's you pass a stack.yaml file as an argument, so it should work now. I'm trying to make it work better though.

**Comment by ndmitchell** [comment]
It does now, please try with weeder-0.1.7 and reopen if it fails. Thanks @pepeiborra  for the trick, works really well.
