### ISSUE TITLE
Deal with TemplateHaskell

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/weeder#14]
@hsyl20 reports: I have a false positive when an import used only in a Template Haskell splice. It is reported as unused.

**Comment by ndmitchell** [comment]
Is it being reported as unused by GHC or by Weeder? In my test case Weeder gets it right while GHC gets it wrong. Can you paste the error message?

**Comment by hsyl20** [comment]
It is reported by Weeder:
```
== Section library ==
Unused import
* Haskus.Arch.X86_64.Linux.Syscalls
  - Haskus.Arch.X86_64.Linux.SyscallTable
```

The `Syscalls` module use a QuasiQuoter from SyscallTable:
```
import Haskus.Arch.X86_64.Linux.SyscallTable
[syscalls| ...|]
```

But the result of the quasi quotation doesn't use anything from SyscallTable.

https://github.com/haskus/haskus-system/blob/fa9a4057c38f1e2808ba570eb57636c51a809c29/src/lib/Haskus/Arch/X86_64/Linux/Syscalls.hs#L19

https://github.com/haskus/haskus-system/blob/fa9a4057c38f1e2808ba570eb57636c51a809c29/src/lib/Haskus/Arch/X86_64/Linux/SyscallTable.hs#L16

**Comment by ndmitchell** [comment]
For expression-level quasi quotes GHC works exactly like i'd expect, but for declaration level quasiquotes I just can't see that the quotation was used. I've noted this as a case I can't do anything for in the module - thanks for the report but you'll need to ignore these entries with a `.weeder.yaml` file.
