### ISSUE TITLE
False positive when reexporting data types

### ISSUE THREAD

**Issue by hsyl20** [ndmitchell/weeder#15]
If I have a module A that reexports a Data type:
```haskell
module A (Word8) where
import Data.Word
```
and a module B that uses it:
```haskell
module B where
import A

main :: IO ()
main = putStrLn (show 25 :: Word8)
```

Weeder wrongly estimates that A is an unused import in B.

However, if a export the whole module it doesn't report it (rightly):
```haskell
module A (module Data.Word) where
import Data.Word
```

(similarly, if A reexports a function instead of a data type, e.g. byteSwap32, Weeder rightly doesn't report it)

**Comment by ndmitchell** [comment]
I can reproduce. Seems that if a data type from another module is exported, the Hi file doesn't record it as being used. I guess the redundant import should probably be ignored if a module exports any types from a different package.

**Comment by ndmitchell** [comment]
I applied the rule that anything exporting a data type from a different package won't get mentioned as an unused import.
