### ISSUE TITLE
False positive to remove imports that are needed for coercions

### ISSUE THREAD

**Issue by ocharles** [ndmitchell/weeder#16]
Using `Data.Coerce.coerce`, we need constructors in scope. In some of my files I have lines like

```haskell
import Foo.Bar as ForCoerce
```

This import is only used to bring all constructors into scope for `coerce` to work. But `weeder` tells me they can be deleted. Deleting them leads to a project that no longer can compiles.

Can provide an example if needed.

**Comment by ndmitchell** [comment]
Is `Foo.Bar` in the package you are defining, or imported from a different package?

**Comment by ocharles** [comment]
Same project (package)

**Comment by ndmitchell** [comment]
Looking at the `.hi` file for something that uses a coerce relationship, it doesn't have an entry saying the module depended upon the module defining the ctor - so changing the data type doesn't make the thing using the coerce recompile. I'm wondering if it would be possible to use that to cheat the compiler somehow into skipping a compilation that was required - but I haven't managed it yet.

**Comment by ndmitchell** [comment]
I don't think there's much I can do, so I've added a section to the readme calling it out as a known false positive, and explaining how to avoid the warnings.
