### ISSUE TITLE
weeder: src/Warning.hs:(80,9)-(84,53): Non-exhaustive patterns in function f

### ISSUE THREAD

**Issue by ocharles** [ndmitchell/weeder#17]
When running this:

```
weeder . > .weeder.yaml
weeder: src/Warning.hs:(80,9)-(84,53): Non-exhaustive patterns in function f
```

My guess is that the redirection creates an empty file, which weeder fails to parse (from glancing at the source code).

**Comment by ndmitchell** [comment]
Which version of weeder are you running? The source spans are a bit weird and the code looks good in this version, but I do remember sorting out that in the near past.

**Comment by ocharles** [comment]
```
weeder --version                                                                                                                                                       ~
Weeder v0.1.2, (C) Neil Mitchell 2017
```

So this does look out of date. I'll update and re-open if this still happens. Sorry for the noise!
