### ISSUE TITLE
Packages with 'extra-dep: true' should not get weeded

### ISSUE THREAD

**Issue by chreekat** [ndmitchell/weeder#18]
Technically you might call this a bug in 'stack query', which lists packages as 'local' when it probably shouldn't. But 'stack query' is marked as experimental. ;)

**Comment by ndmitchell** [comment]
Any suggestion how I should enumerate the packages? Is there a flag to `stack query`? Or do I have to resort to parsing `stack.yaml` myself?

**Comment by mitchellwrosen** [comment]
The format of `stack.yaml` wrt extra deps is about to change according to https://fpcomplete-site-extensible-snapshots.review.gitlab.fpcomplete.com/blog/2017/07/stacks-new-extensible-snapshots. I agree that this is a `stack query` bug =)

**Comment by mitchellwrosen** [comment]
I didn't see any issues about it so I opened commercialhaskell/stack#3258

**Comment by mitchellwrosen** [comment]
@chreekat As a workaround, you can just ignore the extra deps `foo` and `bar` like this:

```yaml
# .weeder.yaml
- package:
  - name: foo
- package:
  - name: bar
```

**Comment by chreekat** [comment]
Thanks @mitchellwrosen !

@ndmitchell I opened this merely to bring the 'stack query' bug to your attention. I think I'll close it with the assumption that it won't bite too many other weeder users.

**Comment by ndmitchell** [comment]
Thanks for tracking this down, reporting, and raising upstream bugs. Until it's fixed, I've added a note at the bottom of the readme.

**Comment by chreekat** [comment]
Happy timing - I have a suspicion that the [upcoming stack changes](https://www.fpcomplete.com/blog/2017/07/stacks-new-extensible-snapshots) will probably fix this (and a bunch of other, unrelated problems I was having with specifying git repos as extra-deps).

**Comment by mitchellwrosen** [comment]
Huh, my workaround actually doesn't seem to work, but the `HEAD` version of stack is more accurate about which packages are locals.

**Comment by mitchellwrosen** [comment]
Nevermind, it does work, I accidentally used `.weeder.yml` in my script instead of `.weeder.yaml`

**Comment by ndmitchell** [comment]
@mitchellwrosen An understandable mistake... Should weeder look for both?

**Comment by mitchellwrosen** [comment]
I wouldn't complain if it did :)

Don't think stack or travis check for both, though

**Comment by ndmitchell** [comment]
Given that stack and travis don't, I won't either. I did make `--verbose` say what is being used though, which hopefully gives a way to debug such failures.
