### ISSUE TITLE
Feature request: output styled as compiler errors

### ISSUE THREAD

**Issue by chreekat** [ndmitchell/weeder#19]
This would allow editor integration, quickly jumping to trouble spots.

**Comment by ndmitchell** [comment]
The errors rarely (if ever?) have position information, so the most I could do is file location, and even then, in many cases they aren't associated with a file. Certainly happy to do something in this area, just not sure what I can do.

**Comment by chreekat** [comment]
I admit I opened this issue without knowing what level of effort it would be. Feel free to *wontfix* it; I'll offer more concrete suggestions if/when they arise. :)

**Comment by ndmitchell** [comment]
I guess I'd have to be able to map modules back to their source files - which is something weeder currently doesn't know about (it maps to the .hi files, which has a somewhat similar structure). But it may just be a case that weeder works at modules/packages, while editors work on files, and the mapping isn't as direct as it would need to be.

**Comment by ndmitchell** [comment]
Closing, but happy to revisit if anyone can figure out a suitable mapping.
