### ISSUE TITLE
Running weeder on IHaskell uses all my RAM and swap

### ISSUE THREAD

**Issue by vaibhavsagar** [ndmitchell/weeder#20]
Does this indicate a memory leak or is it just because IHaskell is a large project?

```
$ git clone https://github.com/gibiansky/IHaskell
$ cd IHaskell
$ weeder
(watch as weeder fills all 16GB of my RAM and 8GB of swap before being killed)
```

I'm using weeder v0.1.6, which is the latest available in LTS-9.0.

**Comment by ndmitchell** [comment]
Does IHaskell work on Windows?

**Comment by vaibhavsagar** [comment]
Does this help? [dump.zip](https://github.com/ndmitchell/weeder/files/1192413/dump.zip)

**Comment by ip1981** [comment]
It's not only IHaskell. It's getting killed for out of memory on 24G RAM and 12G swap with regular stack-based project. Hi, @vaibhavsagar :)

**Comment by ndmitchell** [comment]
@ip1981 Anything public that compiles on Windows? That would make testing easier. Otherwise I'll take a look this weekend.

**Comment by ip1981** [comment]
I'm afraid, no. I tried few packages from Hackage, but wasn't able to spot any leaks.

**Comment by ndmitchell** [comment]
I just released version 0.1.7, which has a `--verbose` flag which prints out a lot of information. Can you please upgrade, try whatever thing is failing, and paste the stdout?

**Comment by vaibhavsagar** [comment]
This seems to have gotten rid of the issue, thanks for the fix!

**Comment by ndmitchell** [comment]
Awesome! Thanks for testing.
