### ISSUE TITLE
Detect unused exports even when exposed

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/weeder#33]
I would love a way to tell weeder to flag functions that are exported, even from exposed modules, but not used by anything.

The use-case is an internal application. It has a library and exposed module(s), but it's a closed world -- nothing outside of this application will ever use these modules. So even though a function is exported from an exposed module, it is still a weed if unused anywhere else in the package.

**Comment by ndmitchell** [comment]
A nice idea in theory, but not possible because of the way GHC works. Basically inside a unit it says what it depends on precisely. Outside that unit it only says which packages it depends on. Weeder uses that information to figure out what is redundant.

One option would be to compile all your projects together in some way? But that's outside the scope of Weeder, as it's likely custom for each project.

**Comment by pbrisbin** [comment]
Ah OK, I guess that makes sense.

I'm wondering more about your suggestion, "One option would be to compile all your projects together in some way". This feature request is purely within a single project, so it makes me wonder if we're misunderstanding each other in some way.

To be totally explicit, the simplest example is:

```hs
-- src/Lib.hs
module Lib
  ( foo
  , bar
  ) where
```

```hs
-- app/Main.hs
import Lib (foo)

main = foo
```

I would like `bar` to be flagged as a weed.

That there would be difficulty here due to how GHC works makes total sense, so I'm fine to see this request closed, assuming my concrete example doesn't trigger any light bulbs.

**Comment by ndmitchell** [comment]
To GHC those are the same as being separate projects - so you could still compile the `src` and `app` together as just an executable project, and then get the complete list. Given it's not supported by GHC I will indeed close this.

**Comment by ip1981** [comment]
May I suggest https://github.com/joshuaclayton/unused ?

**Comment by ndmitchell** [comment]
Good suggestion - I added a link to the README: https://github.com/ndmitchell/weeder/blob/master/README.md#what-else-should-i-use
