### ISSUE TITLE
Add --stack-yaml flag

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/weeder#41]
I run weeder as part of my CI build. I also run a set of builds at different resolvers, to test different sets of dependencies. This is fairly easy to do with `stack --resolver` or `stack --stack-yaml`, but I can't seem to make `weeder` respect that.

As an example, see here: https://circleci.com/gh/thoughtbot/yesod-auth-oauth2/279

Notice how this build is meant to test lts-11.18 / 8.2.2, but...

```
stack exec --stack-yaml stack-lts-11.18.yaml weeder .
Downloading lts-12.2 build plan ...
Downloaded lts-12.2 build plan.
```

Sometimes this happens to work, but other times (as in this case), it fails with:

```
weeder: /root/project/.stack-work/dist/x86_64-linux/Cabal-2.2.0.1: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

Which makes sense because of the compiler mismatch between what's built and what's being weeded (I think).

Is there any way to run weeder at a specific resolver? Ideally it would somehow know it's being run in a `stack exec` with a given resolver/stack.yml and respect that, but having to pass another option to `weeder` itself wouldn't be that bad.

**Comment by ndmitchell** [comment]
I think if you use the `STACK_YAML` environment variable to point at the right `.yaml` file it should work. Does it? Do you think there would be benefit to adding a `--stack-yaml` setting to weeder itself? Would make it more discoverable. I don't think weeder can do much with resolver alone, but if it can, then it could use that.

**Comment by pbrisbin** [comment]
Thanks so much for the quick response! It looks like that worked: https://circleci.com/gh/thoughtbot/yesod-auth-oauth2/286.

I think you're right in that the issue is just discoverability. I had no idea `weeder` would be respecting `STACK_YAML` and, since it does, pairing that with a `--stack-yaml` does seem valuable to me. However, I feel very weakly on that. So weakly that I might not even build it if this were my project :) so I hold no ill-will if you skip it too.

I'm going to close this Issue anyway, since the ENV var works fine for me.

Another interesting "fix" could be if `stack exec`, when given a `--stack-yaml`, would itself set `STACK_YAML` for the command being invoked. But I'm not sure that behavior seems reasonable in isolation, it would've just coincidentally led to the Right Thing in this very specific case.

**Comment by ndmitchell** [comment]
Thanks for the feedback. I think a `--stack-yaml` flag makes a lot of sense, so I'll repurpose this issue to add it.

**Comment by ndmitchell** [comment]
Turns out `weeder stack-lts-11.18.yaml` would have worked all along. I've updated the `--help` output to say:

```
*Main> :main --help
Weeder v0.0, (C) Neil Mitchell 2017-2018

weeder [OPTIONS] [DIR OR stack.yaml]

Common flags:
  -b --build            Build the project first
  -t --test             Run the test suite
  -m --match            Make the .weeder.yaml perfectly match
  -j --json             Output JSON
  -y --yaml             Output YAML
  -s --show-all         Show even ignored warnings
  -d --dist-dir=DIR     Stack dist-dir, defaults to 'stack path --dist-dir'
  -? --help             Display help message
  -V --version          Print version information
     --numeric-version  Print just the version number
  -v --verbose          Loud verbosity
  -q --quiet            Quiet verbosity
```

**Comment by pbrisbin** [comment]
Haha, that's great. I've certainly been in the position of not remembering features I've already built many times.

That actually raises another issue I'd like to get you take on. I hope it's OK I drop this note here, I'm not sure yet if it's worth a real Issue.

We use a multi-package repo, for now let's just call it:

```
root
  haskell
    stack.yaml
    backend/package.yaml
    frontend/package.yaml
```

I was always surprised I could never do `cd haskell/backend && weeder .` or `weeder haskell/backend` and get _only_ those problems in the `backend` package, it always reports issues for the whole project no matter where it's run or the argument I use. Is that a limitation that can't be resolved because of how weeder works?

I only bring it up here because it if _can_ be resolved, there'd then be no way to specify something like `DIR=haskell/backend` and `stack.yaml=haskell/stack.yaml` with this usage -- so perhaps `--stack-yaml` still makes sense.

**Comment by pbrisbin** [comment]
> but if you have a .weeder.yaml file ignoring everything in a whole project is easy

FWIW, that only works if you _always_ want things reported that way. In my case I'm just trying to see things scoped to a given project while I work on it, since otherwise there is a huge output and it's hard to see one project's issues:

```
= Package hubspot-form =
No warnings

= Package frontrow-jobs =
No warnings

= Package school-admin-mailer =
No warnings

= Package db-test-helpers =
No warnings

= Package text-assets-build =
No warnings

= Package text-assets-common =
No warnings

= Package teacher-daily-mailer =
No warnings

= Package school-lead-mailer =
No warnings

= Package build-math-standards =
No warnings

= Package fancy-api =
No warnings

= Package school-report-generator =
Did you see me?

= Package data-gen =
No warnings

= Package school =
No warnings

= Package asana =
No warnings

= Package fr =
No warnings

= Package teacher-mailer =
No warnings

= Package frontrow-app =
No warnings

= Package fr-slack-api =
No warnings

= Package frontrow-types =
No warnings

= Package sendgrid-client =
No warnings

= Package roster-management =
No warnings

= Package frontrow-entities =
No warnings

= Package badge-awarder =
No warnings

= Package aws-xray-client =
No warnings

= Package merge-map =
No warnings

Ignored 845 weeds (pass --show-all to see them)
```

**Comment by ndmitchell** [comment]
You make a good point, let's discuss it in #24.
