### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by joneshf** [ndmitchell/weeder#47]
Thanks for weeder! It's super useful keeping our codebase in check.

Something that's been a bit hard for us as we ramp up more people is interpreting the output from weeder. In our particular case, we have a bunch of exceptions to the rules (`NoImplicitPrelude` means `base` is sometimes marked as unused but the code won't compile otherwise). Those exceptions mean that when there's a weeder error, we get a wall of text to read through and find the fix. We tend to run with `weeder --match .` so it hits all of the code in the repo.

Is there another way to format the output that might make understanding failures easier? If not, would you be open to a PR to reformat the output to make understanding failures easier?

**Comment by ndmitchell** [comment]
Glad it's useful! When you have a failure, shouldn't it just show the failures ignoring what you told to ignore? Or alternatively, do you know about the ignore feature? Ignoring all messages about base should be trivial.

**Comment by ndmitchell** [comment]
Ignore is just the name I call the false positives, so you are using that. I assume you're ignoring the error about `base` being reported as missing? Would be good to see the ugly output.

**Comment by joneshf** [comment]
Sorry for letting this drop off my plate. I no longer work for the previous company and it looked like they were going to dump weeder instead of attempting to help diagnose/fix this. Closing for now since I've less stake in the game.

Will come back and help fix if I end up using weeder again though.

**Comment by ndmitchell** [comment]
Thanks for letting me know. Shame they're going to stop using it, since I suspect it's easily fixable, but hey ho.
