### ISSUE TITLE
How do I install weeder?

### ISSUE THREAD

**Issue by eschnett** [ndmitchell/weeder#5]
I'm using Stack, but am not yet very familiar with it. I assume that I should add `weeder` as a package to my project, and then e.g. issue `stack install weeder`?

Or do I need to install `weeder` independent of my project? However, given that Stack even installs `ghc` as part of a project, that would seem strange.

**Comment by ndmitchell** [comment]
First install Weeder - the way I did that was `cabal update && cabal install weeder`. I believe if you go to your existing project and type `stack install weeder` that should work too. There is no requirement to add `weeder` as a package in your project - moreover it will probably be actively harmful.

Once you have installed weeder, run `stack exec -- weeder .` and it will run `weeder` for you.

**Comment by bergmark** [comment]
I did this outside a stack project: `stack install weeder-1.0.2 --resolver lts-8`

**Comment by eschnett** [comment]
Thanks! I needed to issue
```
stack install weeder-1.0.2
stack install weeder
```
Both were necessary in this order.

**Comment by bergmark** [comment]
That sounds strange, what made you need both?

**Comment by eschnett** [comment]
Doing the second only lead to an error (couldn't find `weeder`). Doing the first only did something, but then didn't install anything. Then issuing the second command again installed `weeder`...

**Comment by bergmark** [comment]
if you can reproduce this it would be nice to have a report on the stack issue tracker.

**Comment by ndmitchell** [comment]
If anyone can tell me the public recommended way of installing a Haskell package nowadays I'd be most grateful. I tend to recommend `cabal update && cabal install weeder` for all my other packages, but since this one does depend on `stack` having been run, it seems to make more sense to describe in terms of that. Alas, that seems way more confusing than the `cabal` recipe.

**Comment by bergmark** [comment]
I think the best compromise is `stack install weeder --resolver nightly`, it's not guaranteed to work forever but if the package is in the snapshot it's unlikely that it would fail.

**Comment by ndmitchell** [comment]
Documentation improved as per @bergmark's suggestion.
