### ISSUE TITLE
Cannot run weeder using --resolver nightly

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/weeder#54]
I'm running into some issues on CI when building on Stackage nightly. Here is the full case: https://app.circleci.com/jobs/github/pbrisbin/bugsnag-haskell/852.

Since nightly moves, I use the following `stack-nightly.yaml` on CI:

```yaml
# overriden by --resolver on CI
resolver: nightly-2019-11-29

# Fix weeder with stack-2.0
ghc-options: { "$locals": -ddump-to-file -ddump-hi }
```

set via `STACK_YAML`. Since you can't put `resolver: nightly` in `stack.yaml`, I pass `--resolver nightly` on CI, as noted. This drift is causing `weeder` to not function.

In the *Lint* step of the build, I see

```console
% stack exec --no-terminal --resolver nightly weeder .
Getting project config file from STACK_YAML environment
Selected resolver: nightly-2020-02-26
Stack has not been tested with GHC versions above 8.6, and using 8.8.2, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
```

Notice resolver `nightly-2020-02-26`, ghc `8.8.2`, and Cabal `3.0.1.0`, which is all correct. But then (I assume) `weeder` is going to re-execute `stack`. It loses the `--resolver` argument and is using the resolver in the bare `stack.yaml`.

So, I see **this** output:

```console
Getting project config file from STACK_YAML environment
Stack has not been tested with GHC versions above 8.6, and using 8.8.1, this may fail
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-8.8.1 ...
ghc-8.8.1: download has begun
ghc-8.8.1:   40.06 MiB / 186.83 MiB ( 21.44%) downloaded...
ghc-8.8.1:   81.84 MiB / 186.83 MiB ( 43.81%) downloaded...
ghc-8.8.1:  121.86 MiB / 186.83 MiB ( 65.22%) downloaded...
ghc-8.8.1:  158.23 MiB / 186.83 MiB ( 84.69%) downloaded...
ghc-8.8.1:  186.83 MiB / 186.83 MiB (100.00%) downloaded...
Downloaded ghc-8.8.1.
Unpacking GHC into /root/.stack/programs/x86_64-linux/ghc-8.8.1.temp/ ...
Configuring GHC ...
Installing GHC ...
Installed GHC.
Stack has not been tested with Cabal versions above 2.4, but version 3.0.0.0 was found, this may fail
Getting project config file from STACK_YAML environment
```

We've now got ghc `8.8.1` and Cabal `3.0.0.0`. As you might expect, `weeder` fails:

```
weeder: /root/project/.stack-work/dist/x86_64-linux/Cabal-3.0.0.0: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

Is there some way to make this function? To get `weeder` to pass `--resolver nightly` along when it re-executes Stack?

My current workaround is easy: don't lint the Nightly CI job, but I thought this was an interesting enough edge case to report.

**Comment by ndmitchell** [comment]
Shame! The plan is to replace weeder with weeder 2, so I'm not massively inclined to do a huge amount of significant rework for it. I wonder how close Weeder 2 is @ocharles?

**Comment by ocharles** [comment]
...fairly? It's in a kind of usable state, so people could certainly start playing around with it. I might look at publishing some kind of prototype that people can try. Maybe I should try weeding some big known executables like `ghcide` and stuff, and once I'm happy with a golden suite, I'll release

**Comment by ndmitchell** [comment]
:( - the world is crying out for it. Shame about the TH issues...

**Comment by ocharles** [comment]
I'll be at Zurihac this year, so if I haven't got it by then, I can hopefully focus on it then!

**Comment by ndmitchell** [comment]
Weeder 2.0 is being developed at https://github.com/ocharles/weeder so I suggest you go see if that fixes your issues.

**Comment by pbrisbin** [comment]
Closing as I've been happily using weeder-2.0 for ages now.
