### ISSUE TITLE
Warnings about orphan imports

### ISSUE THREAD

**Issue by bergmark** [ndmitchell/weeder#7]
Can be seen on this aeson branch https://github.com/bos/aeson/tree/weeder-instances

Weeder warns on these test suite modules:
```
Excessive other-modules entry
* DataFamilies.Instances
* Functions
* Instances
```

But `Instances` is definitely used, the import is `import Instances ()`.

How about not warning on these imports, or do you think it's better to manually ignore them?

Edit: `Functions` actually exports identifiers but is only used by `Instances` so that makes things slightly more inconvenient ;-)

**Comment by ndmitchell** [comment]
I tweaked the code so that modules imported, but where nothing named from the import is used, still don't get marked as pointless. With that, all 3 modules drop off the list.

**Comment by ndmitchell** [comment]
Are you happy to continue experimenting with HEAD? If that's in any way inconvenient, I'll make a release. Otherwise I'll probably wait for you to stumble into a few addition issues before I make the release.

**Comment by bergmark** [comment]
I'll play with HEAD!
