### ISSUE TITLE
Promote weeder

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/weeder#9]
Weeder doesn't really exist until I announce it to people. I should announce it once it's useful and is free of all the obvious simple defects. @bergmark - any thoughts as to whether we've reached that milestone? Anything else that is annoying you about weeder? What else needs doing before https://github.com/bos/aeson/tree/weeder-instances is merged? (if that is indeed your plan)

**Comment by bergmark** [comment]
The aeson library is free of weeds so I don't think I'll run across any other issues. I created a PR (https://github.com/bos/aeson/pull/548). I still need to set up the travis job + fix a few remaining weeds in the test suite.

For weeder itself: Do you distribute travis usable binaries as you do with hlint? That'd be useful to have. Otherwise I'll just go the `stack install` route.

**Comment by ndmitchell** [comment]
I plan to distribute travis binaries just like HLint - assuming weeder-0.1.3 is working I'll upload binaries, roll it out in my travis scripts and get all my projects weeder clean and then announce.

**Comment by ndmitchell** [comment]
For weeder, there are now binaries which work exactly like HLint on Travis - namely:

    wget https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh -O - --quiet | sh -s

Give it a go and let me know if it works for you or not.

**Comment by bergmark** [comment]
Thanks! I'll try it out tonight.

**Comment by bergmark** [comment]
Sorry for the delay,

I'm having some issues since I'm using a system ghc:

```
+stack setup --resolver lts-8
[...]
Installed GHC.
[...]
+wget https://raw.github.com/ndmitchell/weeder/master/misc/travis.sh -O - --quiet
+sh -s
Downloading and running weeder...
######################################################################## 100.0%
weeder: /home/travis/build/bos/aeson/attoparsec-iso8601/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0: getDirectoryContents: does not exist (No such file or directory)
```

**Comment by ndmitchell** [comment]
I guess that stack path changes based on the resolver argument. I could get weeder to take an explicit stack path argument.

**Comment by ndmitchell** [comment]
I just released weeder-0.1.4 which allows you to pass `--dist-dir` with the dist-dir, which if you set to `stack path --dist-dir --resolver lts-8` should work.

**Comment by ndmitchell** [comment]
I've now cleared out my list - will do the first blog post shortly.

**Comment by ndmitchell** [comment]
Post written - http://neilmitchell.blogspot.co.uk/2017/06/announcing-weeder-dead-export-detection.html
